config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  resources :kebabs do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[destroy]

  root to: 'kebabs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kebab.rb
class Kebab < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, uniqueness: true, presence: true
  validates :description, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

  extend FriendlyId
  friendly_id :name, use: :slugged

  acts_as_taggable_on :bread_category

  include PgSearch::Model
  pg_search_scope :search_by_name_and_address,
    against: [ :name, :address ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def average_rating
    reviews.average(:overall_rating)
  end

  def bread_avg
    reviews.average(:bread_rating)
  end

  def fries_avg
    reviews.average(:fries_rating)
  end

  def meat_avg
    reviews.average(:meat_rating)
  end

  def sauces_avg
    reviews.average(:sauces_rating)
  end

  def quantity_avg
    reviews.average(:quantity_rating)
  end

  def quality_price_ratio_avg
    reviews.average(:quality_price_ratio)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :kebab

  validates :author, presence: true
  validates :content, presence: true
  validates :bread_rating, presence: true
  validates :fries_rating, presence: true
  validates :meat_rating, presence: true
  validates :sauces_rating, presence: true
  validates :quantity_rating, presence: true
  validates :quality_price_ratio, presence: true
  validates :overall_rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/kebabs_controller.rb
class KebabsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_kebab, only: %i[show edit update destroy]

  def index
    if params[:query].present?
      sql_query = 'name ILIKE :query OR address ILIKE :query'
      @kebabs = Kebab.where(sql_query, query: "%#{params[:query]}%")
    else
      @kebabs = Kebab.where.not(latitude: nil, longitude: nil)
    end
    @markers = @kebabs.map do |kebab|
      {
        lat: kebab.latitude,
        lng: kebab.longitude,
        infoWindow: { content: render_to_string(partial: '/kebabs/info_window', locals: { kebab: kebab }) }
      }
    end
  end

  def show
    @reviews = Review.all
    @review = Review.new
    @related_kebabs = @kebab.find_related_bread_category
  end

  def new
    @kebab = Kebab.new
  end

  def create
    @kebab = Kebab.new(kebab_params)
    if @kebab.save
      flash[:notice] = 'Kebab successfully created'
      redirect_to kebab_path(@kebab)
    else
      flash.now[:alert] = 'Problem when creating Kebab'
      render :new
    end
  end

  def edit; end

  def update
    if @kebab.update(kebab_params)
      flash[:notice] = 'Kebab updated'
      redirect_to kebab_path(@kebab)
    else
      flash.now[:alert] = 'Problem when updating Kebab'
      render :update
    end
  end

  def destroy
    @kebab.destroy
    redirect_to kebabs_path
  end

  private

  def kebab_params
    params.require(:kebab).permit(:name, :address, :description, :photo, bread_category_list: [])
  end

  def set_kebab
    @kebab = Kebab.friendly.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[new create]

  def new
    @kebab = Kebab.friendly.find(params[:kebab_id])
    @review = Review.new
  end

  def create
    @reviews = Review.all
    @kebab = Kebab.friendly.find(params[:kebab_id])
    @related_kebabs = @kebab.find_related_bread_category
    @review = Review.new(review_params)
    @review.kebab = @kebab
    if @review.save
      respond_to do |format|
        format.html { redirect_to kebab_path(@kebab, anchor: "review-#{@review.id}") }
        format.js
      end
      flash[:notice] = 'Votre commentaire a été ajouté'
    else
      respond_to do |format|
        format.html { render 'kebabs/show'}
        format.js
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to kebab_path(@review.kebab)
  end

  private

  def review_params
    params.require(:review).permit(:author, :content, :bread_rating, :fries_rating, :meat_rating, :sauces_rating, :quantity_rating, :quality_price_ratio, :overall_rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar_for(kebab)
    kebab_pic = kebab
    if kebab_pic.photo.attached?
      kebab_default_img = cl_image_tag(kebab.photo.key, width: 140, crop: :fill, class: 'kebab-pic', alt: 'Kebab picture - Passion Döner')
    else
      kebab_default_img = image_tag('kebab_default.png', class: 'kebab-pic', alt: 'Kebab picture - Passion Döner', width: 140)
    end
    kebab_default_img
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/kebabs/_info_window.html.erb
<div class="info-window-wrapper">
  <%= link_to kebab_path(kebab) do %>
    <h4><%= kebab.name %></h4>
  <% end %>
  <div class="tags-wrapper" id="map-tags">
    <% kebab.bread_category_list.each do |tag| %>
      <p class="tags" id="tags-small"><%= tag %></p>
    <% end %>
  </div>
  <div class="infoWindow-stars">
    <% if  kebab.reviews.present? %>
      <% count = 0 %>
      <% 5.times do %>
        <% if kebab.average_rating.round > count %>
          <span class="stars stars-small star-colored"></span>
        <% else %>
          <span class="stars stars-small star-blank"></span>
        <% end %>
        <% count += 1 %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/kebabs/_kebab_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-10 mx-auto">
      <%= simple_form_for(@kebab) do |k| %>
        <div class="wrap-input">
          <%= k.input :name, input_html: {class: 'form-inputs kebab_new_inputs'}, placeholder: "Kebab's Delight" %>
        </div>
        <div class="wrap-input"> <%= k.input :address, input_html: {class: 'form-inputs kebab_new_inputs'}, placeholder: "75 cours de verdun 75008 Paris" %></div>
        <div class="wrap-input">
          <%= k.input :bread_category_list, as: :check_boxes, collection: [ "Galette", "Pita", "Pain", "Turc" ], input_html: {class: 'form-check form-check-inline'}, label: "Bread Category" %>
        </div>
        <div class="wrap-input">
          <%= k.input :description, input_html: {class: 'form-inputs', id:'text-input'}, label: "Description"%>
        </div>
        <div class="photo-wrapper">
          <%= k.input :photo, as: :file, input_html: { class: 'd-none' , id: 'photo-input'}, label_html: { class: 'upload-photo'}, label: '📷 Upload a photo' %>
          <%= image_tag "", width: 300, class: "hidden", id: "photo-preview" %>
        </div>
        <%= k.submit class: 'btn-kebab_new' %>
      <% end %>
    </div>
  </div>
</div>

app/views/kebabs/edit.html.erb
<div class="container">
  <h1 class="title">Edit <%= @kebab.name %></h1>
  <%= render 'kebab_form', kebab: @kebab %>
  <hr>
  <%= link_to kebabs_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>

app/views/kebabs/index.html.erb
<div class="container-fluid index-page">
  <h1 class="title">Passion Döner</h1>
  <% if user_signed_in? && current_user.admin? %>
    <div class="cta-wrapper">
      <%= link_to 'Add a Kebab', new_kebab_path, class: 'gradient-button text-center'%>
    </div>
  <% end %>
  <div class="search-form-nav">
    <%= form_tag kebabs_path, method: :get, class: "search-form-control form-group" do %>
      <%= label_tag 'query', nil, class: 'sr-only' %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control string required index_search",
        placeholder: "Search a Kebab" %>
      <%= button_tag(type: "submit", class: "btn btn-flat") do %>
        <i class="fas fa-search"></i> Search
      <% end %>
    <% end %>
    <%= link_to request.path, class:"cancel-button" do %>
      <span class="sr-only">Reset search</span>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
  <div
  id="map"
  style="
  height: 400px;
  margin:auto;"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  data-markers="<%= @markers.to_json %>"
></div>
  <div class="kebabs_all-wrapper">
    <% if @kebabs.empty? %>
      <h6 class="text-center kebab-not_found">sorry we did not find any Kebab...</h6>
    <% else %>
      <div class="kebabs-cards">
        <% @kebabs.each do |kebab| %>
          <%= link_to kebab_path(kebab), class: 'card-product' do %>
            <%= avatar_for(kebab)%>
            <div class="card-product-infos">
              <h2><%= kebab.name %></h2>
              <p class="kebab-address kebab-address-small"><%= kebab.address %></p>
              <div class="card-right-section">
                <div class="tags-wrapper tags-index">
                  <% kebab.bread_category_list.each do |tag| %>
                    <p class="tags tags-small"><%= tag %></p>
                  <% end %>
                </div>
                <div class="stars-wrapper stars-index">
                  <% if  kebab.reviews.present? %>
                    <% count = 0 %>
                    <% 5.times do %>
                      <% if kebab.average_rating.round > count %>
                        <span class="stars-small star-colored"></span>
                      <% else %>
                        <span class="stars-small star-blank"></span>
                      <% end %>
                      <% count += 1 %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/kebabs/new.html.erb
<div class="back-to-list">
  <%= link_to kebabs_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>
<div class="container page-wrapper">
  <h1 class="title">New Kebab</h1>
  <%= render 'kebab_form', kebab: @kebab %>
</div>

app/views/kebabs/show.html.erb
<%# View specific meta tags %>
<% content_for :meta_title, "#{@kebab.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @kebab.description %>
<% if @kebab.photo.attached? %>
  <% content_for :meta_image, url_for(@kebab.photo) %>
<% else %>
  <% content_for :meta_image, image_url("kebab_default.png") %>
<% end %>
<div class="back-to-list">
  <%= link_to kebabs_path do %>
    <i class="fa fa-history"></i> Back to list
  <% end %>
</div>
<div class="container page-wrapper">
  <h1 class="title"><%= @kebab.name %></h1>
  <p class="kebab-address"><%= @kebab.address %></p>
  <div class="kebab-pic-wrapper">
    <%= avatar_for(@kebab)%>
  </div>
  <div class="kebab-description">
    <p><%= @kebab.description %></p>
  </div>
  <div class="kebab_actions-wrapper">
    <% if user_signed_in? && current_user.admin? %>
      <hr>
      <%= link_to edit_kebab_path(@kebab), class: 'btn btn-primary' do %>
        <i class="fas fa-edit"></i> Edit kebab
      <% end %>
      <%= link_to kebab_path(@kebab), method: :delete, data: { confirm: "Delete #{@kebab.name}?" }, class: 'btn btn-danger' do %>
        <i class="fas fa-trash-alt"></i> Delete
      <% end %>
      <hr>
    <% end %>
  </div>
</div>
<div class="rating-section container-fluid">
  <div class="kebab-rating-container">
    <h4 class="rating-title">Our community rated this Kebab</h4>
    <div class="kebab-rating">
      <div class="stars-wrapper">
        <% if  @kebab.reviews.present? %>
          <% count = 0 %>
          <% 5.times do %>
            <% if @kebab.average_rating.round > count %>
              <span class="stars star-colored"></span>
            <% else %>
              <span class="stars star-blank"></span>
            <% end %>
            <% count += 1 %>
          <% end %>
        </div>
        <div class="review-nb">
          <% if @kebab.reviews.count == 1 %>
            <span class="rating-txt">(<%= @kebab.reviews.count %> review)</span>
          <% else %>
            <span class="rating-txt">(<%= @kebab.reviews.count %> reviews)</span>
          <% end %>
        <% else %>
          <p class="no-review-msg">Be the first to let a rating</p>
        <% end %>
      </div>
    </div>
    <div class="rating-details">
      <div class="flex-wrapper">
        <div class="bread_rating avg_rating">
          <p>Bread:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.bread_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
        <div class="fries_rating avg_rating">
          <p>Fries:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.fries_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="flex-wrapper">
        <div class="meat_rating avg_rating">
          <p>Meat:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.meat_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
        <div class="sauces_rating avg_rating">
          <p>Sauces:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.sauces_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="flex-wrapper">
        <div class="quantity_rating avg_rating">
          <p>Quantity:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.quantity_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
        <div class="quality_price_rating avg_rating">
          <p>Quality / Price:</p>
          <% if  @kebab.reviews.present? %>
            <% count = 0 %>
            <% 5.times do %>
              <% if @kebab.quality_price_ratio_avg.round > count %>
                <span class="stars-small star-colored"></span>
              <% else %>
                <span class="stars-small star-blank"></span>
              <% end %>
              <% count += 1 %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="rate-btn">
      <button type="button" class="btn btn-flat" id="review-btn" data-toggle="modal" data-target="#modalReview">
        Rate this Kebab
      </button>
    </div>
  </div>
  <div class="reviews_content-wrapper">
    <h4 class="rating-title">Latest Reviews</h4>
    <% if  @kebab.reviews.present? %>
      <% @reviews.limit(10).order("created_at asc").each do |review| %>
        <%= render 'reviews/show', review: review %>
      <% end %>
    <% else %>
      <p class="no-review-msg">No reviews yet</p>
    <% end %>
  </div>
</div>
<div id="new-review">
  <div class="modal fade" id="modalReview" tabindex="-1" role="dialog" aria-labelledby="modalReview" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <div class="modal-header">
          <h2 class="modal-title">Rate this Döner</h2>
        </div>
        <div class="modal-body">
          <%= render 'reviews/new', review: @review, kebab: @kebab %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- <div class="related_kebab">
    <h3>Kebabs with same bread style</h3>
    <ul>
      <%# @related_kebabs.each do |r| %>
        <li><%#= r.name %></li>
      <%# end %>
    </ul>
  </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Passion Döner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= favicon_link_tag %>
    <%# handle loading of font avoiding render blocking (cf lighthouse) %>
    <link rel="preconnect"
      href="https://fonts.gstatic.com"
      crossorigin />
    <!-- We use the full link to the CSS file in the rest of the tags -->
    <link rel="preload"
      as="style"
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&family=Permanent+Marker&display=swap" />
    <link rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&family=Permanent+Marker&display=swap"
      media="print" onload="this.media='all'" />
    <noscript>
      <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;700&family=Permanent+Marker&display=swap" />
    </noscript>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js" integrity="sha512-gauu0VKZq9ry8hOZHgNpcB2ogbSDojs+XLDItpOLY0IyA+KigeuT/suwSdPgfU/TGYLAn4Nan4OeaCa/UPr70Q==" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <div id="root"></div> -->

app/views/reviews/_new.html.erb
<div class="review_section" data-turbolinks="false">
  <div class="container">
    <div class="mx-auto">
      <%= simple_form_for([kebab, review], remote: true,  html: { class: "review_form" }) do |f| %>
        <%= f.error_notification %>
        <div class="wrap-input">
          <%= f.input :author, label: "Name",  placeholder: "Kürşat Şahin", input_html: {id: "author_name", class: "form-inputs" } %>
        </div>
        <div class="wrap-input">
          <%= f.input :bread_rating, as: :select, collection: 1..5, label: "Bread", input_html: {class: "rating_fields"} %>
          <%= f.input :meat_rating, as: :select, collection: 1..5, label: "Meat", input_html:{class: "rating_fields"} %>
          <%= f.input :fries_rating, as: :select, collection: 1..5, label: "Fries", input_html: {class: "rating_fields"} %>
        </div>
        <div class="wrap-input">
          <%= f.input :sauces_rating, as: :select, collection: 1..5, label: "Sauces", input_html: {class: "rating_fields"} %>
          <%= f.input :quantity_rating, as: :select, collection: 1..5, label: "Quantity", input_html: {class: "rating_fields"}%>
          <%= f.input :quality_price_ratio, as: :select, collection: 1..5, label: "Quality/price", input_html: {class: "rating_fields"} %>
        </div>
        <div class="wrap-input">
          <%= f.input :overall_rating, as: :select, collection: 1..5, label: "Overall rating", input_html: {class: "rating_fields"} %>
        </div>
        <div class="wrap-input">
          <%= f.input :content, label: "Comment your review", input_html: {id: "review-text", class: "form-inputs" } %>
        </div>
        <div class="wrap-input" id="create_kebab">
          <%= f.button :submit, class: "btn btn-ghost" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_show.html.erb
<div class="review-box" id="review-<%= review.id %>">
  <div class="box-flex">
    <p class="review-author"><%= review.author %></p>
    <p class="review-date"><%= review.created_at.strftime("%d/%m/%Y")%></p>
  </div>
  <div class="review-overall-avg">
    <% if  @kebab.reviews.present? %>
      <% count = 0 %>
      <% 5.times do %>
        <% if @kebab.average_rating.round > count %>
          <span class="stars-small star-colored"></span>
        <% else %>
          <span class="stars-small star-blank"></span>
        <% end %>
        <% count += 1 %>
      <% end %>
    <% end %>
  </div>
  <br>
  <p class="review-content"><%= review.content %></p>
</div>

app/views/reviews/create.js.erb
<% if @review.errors.any? %>
  $('.modal-body').html('<%= j render "reviews/new", kebab: @kebab, review: @review %>');
<% else %>
  location.reload();
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="separator-gradient-footer"></div>
<footer class="footer">
  <div class="logo-footer">
    <%= link_to root_path do %>
      <span class="sr-only">Go to homepage</span>
      <%= image_tag "logo.jpg", alt: "Passion Döner  logo", width: 80 %>
    <% end %>
  </div>
  <div class="copyright">
    <p>
      &copy;
      <span>Passion Döner</span>
      <span><%= Date.today.year%>.</span>
      <span>All rights reserved</span>
    </p>
  </div>
  <div id="colophon">
    <p>
      Website coded by
      <a
        href="https://www.alexgwebdev.com/"
        target="_blank"
        rel="noopener noreferrer"
      >
        <img
          src="https://res.cloudinary.com/dcf4y5ngp/image/upload/v1595504600/logo_3d_colors.png"
          alt="Alex G - Web developer"
          height="40"
          class="flip"
        />
        </a>
      </p>
    </div>
  </footer>

app/views/shared/_navbar.html.erb
<nav class="main-navbar stroke">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "logo.jpg", alt: "Passion Döner  logo", width: 70 %>
      <span class="sr-only">Go to homepage</span>
    <% end %>
  </div>
  <div class="nav-flex-right">
    <button class="color_btn light--hidden" aria-label='Toggle Light mode'>
      <i class="fas fa-sun"></i>
      Light Mode
    </button>
    <button class="color_btn dark--hidden" aria-label='Toggle dark mode'>
      <i class="fas fa-moon"></i>
      Dark Mode
    </button>
    <div class="d-none d-sm-block">
      <div class="links-section">
        <% if user_signed_in? %>
          <%= link_to t(".profile", default: "My account"), edit_user_registration_path, class: "navbar-item navbar-link" %>
          <%= link_to t(".sign_out", default: "Log out"),destroy_user_session_path, method: :delete, class: "navbar-item navbar-link" %>
        <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-item navbar-link" %>
        <% end %>
      </div>
    </div>
    <div class="dropdown d-block d-sm-none">
      <i class="fas fa-bars" id="navbarDropdown" data-toggle="dropdown"></i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <%= link_to t(".profile", default: "My account"),edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to t(".sign_out", default: "Log out"),destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "dropdown-item"%>
        <% end %>
      </div>
    </div>
  </div>
</nav>